
name: Whatever Template Salvo

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: workflows/test-workflow

      - name: Run the workflow defined by salvo
        run: echo "Did it work?"